# Project Name  : Mercari Code test
# Services Name : Login JWT
# Maintainer    : Derandi Hermanda

version: '3'

volumes:
  auth_services_data: {}
  code_src_data: {}

networks:
  auth_services-net:
      external: false

services:
  mercari_auth_servcies:
    container_name: "mercari_auth_servcies"
    build:
      context: .
      dockerfile: ./src/Config/Dockerfile
    restart: on-failure
    networks:
      - auth_services-net
    volumes:
      - code_src_data:/service/
    depends_on:
      - mercari_postgres_auth_servcies
#    deploy:
#      replicas: 0
#      mode: replicated
    command: bash -c
      "./wait-postgres.sh
      && flask db init
      && flask db migrate
      && flask db upgrade
      && /usr/local/bin/gunicorn --bind=0.0.0.0:5000 -w 3 --worker-class="egg:meinheld#gunicorn_worker" app:app --timeout 600 --capture-output --log-level debug"

  mercari_postgres_auth_servcies:
    container_name: "mercari_postgres_auth_servcies"
    image: postgres:11-alpine
    restart: on-failure
    env_file: src/Config/db.env
    ports:
      - '7000:5432'
    networks:
      - auth_services-net
    volumes:
      - auth_services_data:/var/lib/postgresql/data
  
  mercari_reverseproxy_auth_services:
    container_name: "mercari_reverseproxy_auth_services"
    image: nginx:latest
    volumes:
      - ./src/Config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - auth_services-net
    depends_on:
      - mercari_auth_servcies
    ports:
      - '8000:5000'
    restart: always
  
  mercari_redis_auth_services:
    container_name: "mercari_redis_auth_services"
    image: redis:alpine
    restart: on-failure
    networks:
      - auth_services-net